// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiL9W_qOomvOfEoM3bq2iownVaUrhzcuo',
    appId: '1:987633220641:android:69dc69c86cabf07fb57760',
    messagingSenderId: '987633220641',
    projectId: 'bridgeit-offcial',
    databaseURL: 'https://bridgeit-offcial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bridgeit-offcial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFI9Hidnu5Dkd0F5jw7xu8AaZKyT8fi0',
    appId: '1:987633220641:ios:5aefe9aae68c7a11b57760',
    messagingSenderId: '987633220641',
    projectId: 'bridgeit-offcial',
    databaseURL: 'https://bridgeit-offcial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bridgeit-offcial.firebasestorage.app',
    iosBundleId: 'com.example.projectGraduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqFI9Hidnu5Dkd0F5jw7xu8AaZKyT8fi0',
    appId: '1:987633220641:ios:5aefe9aae68c7a11b57760',
    messagingSenderId: '987633220641',
    projectId: 'bridgeit-offcial',
    databaseURL: 'https://bridgeit-offcial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bridgeit-offcial.firebasestorage.app',
    iosBundleId: 'com.example.projectGraduation',
  );
}